# Singular Value Decomposition (SVD): Descomposicion en valores singulares
Hasta el momento hemos visto dos formas de "factorizar" (descomponer) una matriz  como el producto de otras tres matrices. Por conveniencia.

1. El teorema de descomposicion espectral:
$$ A = Q \Lambda Q^T$$
donde $Q$ es ortogonal con las columnas los atuvectores de $A$ y $\Lambda$ diagonal con los autovalores de $A$. Restriccion: $A$ es autoadjunta (cuadrada)

2. El teorema de diagonalizacion
$$ A = P \Lambda P^{-1}$$
Donde $P$ es una matriz con columnas los autovectores de $A$ y $\Lambda$ diagonal con los autovalores. Restriccion: $A$ debe tener autovectores linealmente independientes.  Que pasa si los autovectores de $A$ no son linealmente independientes. Entonces

$$ A = P J P^{-1}$$
donde $J$ se llama la matriz de
[Jordan](https://en.wikipedia.org/wiki/Jordan_normal_form).
o forma canonica de Jordan.


Ahora
3.0 La Matriz $A$ para SVD puede ser **cualquiera**. Restricciones ninguna.

3. El SVD: Esta clase
## Teorema SVD:
Singular Value Decomposition.

**Teorema 2.3.1** (SVD)
Dada una matriz $A \in \mathbb{C}^{m \times n}$, exiten matrices ortogonales $U \in \mathbb{C}^{m \times m}$, $V \in \mathbb{C}^{n \times n}$ y una matriz diagonal $\Sigma \in \mathbb{R}^{m \times n}$ con componentes $\sigma_{ii} \ge 0$, como es diagonal, las componentes por fuera de la diagonal son 0, y podemos renombrar los elementos de la diagonal $\sigma_i$, $i=1, \cdots, \min \{m,n\}$
donde
$$A = U \Sigma V^* $$

**Prueba**: Esta prueba se debe a Cornelius Lanczos (Hungaro)
bibliografia en la pagina de la UVirtual.

Primero escriba una matriz extendiada $S$

$$S = \begin{pmatrix} 0 &|& A \\ - &-&-\\ A^* &|& 0  \end{pmatrix}  $$

Donde $S \in \mathbb{C}^{m \times n}$.
Ahora $S$ es autoajunta (pruebelo) por lo tanto usando el teorema de descomposicoin espectral


$$S w_i = \lambda_i w_i $$
con

$$ w_i = \binom{u_i}{v_i} $$
donde $u_i \in \mathbb{C}^m$ y $v_i \in \mathbb{C}^n$.
Ademas $w_i$ son **ortogonales** (por el teorema de descomposicion espectral).

Multiplicar por bloques
$$S w_i =  \binom{A v_i }{A^* u_i} $$

De forma que

$$A v_i = \lambda_i u_i \tag{1}  $$
$$A^* u_i = \lambda_i v_i  \tag{2}  $$

Los $\lambda_i$ son reales (TDE).
Multiplicamos la primera de estas dos a izquierda por $A^*$ y la segunda por $A$

$$A^* A v_i = \lambda_i A^* u_i  $$
$$A A^* u_i = \lambda_i A v_i  $$

$$A^* A v_i = \lambda_i \lambda_i v_i  = \lambda_i^2 v_i  $$
$$ A A^* u_i = \lambda_i \lambda_i u_i = \lambda_i^2 u_i $$

Es decir $v_i$ son autovectores de $A^* A$
Es decir $u_i$ son autovectores de $A A^*$
y que $\lambda_i$ son autovalores de ambos $A^*A$ y de $A A^*$.

Tenemos dos matrices $A^* A \in \mathbb{C}^{n \times n}$
 $A A^* \in \mathbb{C}^{m \times m}$
Los autovalores $\lambda_1, \lambda_2 , \cdots, \lambda_p$ con
$p = \min \{ m, n \}$ no estan garantizados positivos.  Pueden haber algunos que sean 0 . Sea $r$ el ultimo autovalor que no es 0. Precisamente los autovalores que son 0 noquean (knock-down) esa dimension.  

Vamos a escribir la matrice $U$ como los autovectores de $A^*A$,
la matrice $V$ como los autovectores de $AA^*$
Definamos la matriz $U_r$ como aquellas columnas que pertenecen a autovalores no 0.
Definamos la matriz $U_0$ como aquellas columnas que pertenecen a autovalores iguales  0.

Definamos la matriz $V_r$ como aquellas columnas que pertenecen a autovalores no 0.
Definamos la matriz $U_r$ como aquellas columnas que pertenecen a autovalores iguales  0.
Sea $\Lambda_r$ la matriz $r \times r$ de autovalores no cero.  
Es decir, de (2) y teorema clase anterior.

$$A^* U_r = V_r \Lambda_r $$
$$A^* U_0 = 0 $$

Igualmente de (1)
$$A V_r = U_r \Lambda_r $$
$$A V_0 = 0 $$

Aca recuerdo la multiplicion por bloques (tarea de lectura)

$$A V = A [ V_r | V_0 ] = [A V_r | A V_0] = [U_r \Lambda_r | 0] = [ U_r \Lambda_r + U_0 \times 0 | U_r \times 0 + U_0 \times 0 ] = U \Sigma  $$
donde
$$\Sigma = \begin{pmatrix} \Lambda_r & | & 0  \\ --&-&-- \\ 0 &|& 0  \end{pmatrix}  $$

De forma que si

$$AV = U\Sigma $$
y como $V$ es ortogonal multiplicamos a ambos lados (a derecha) por $V^*$ y obtenemos

$$ A = U \Sigma V^* $$
La matriz $\Sigma$ tiene la submatriz $\Lambda_r$ que es cuadrada de orden $r \times r$. A los autovalores (positivos) son $\lambda_i = \sqrt{\lambda_i^2}$.
Pregunta por que no $| \lambda_i |$.  Definicion $\lambda_i = \sqrt{\lambda_i^2} = \sigma_i$ se llaman **valores singulares**.

**Ejemplo 2.3.1**: Encuentre la SVD de la siguiente matriz

$$A = \begin{pmatrix} 1 & 0 & 3 \\  1 & 2 & 4 \end{pmatrix} $$
Redondee los resultados a dos cifras decimales.

**Algoritmo**:
1. Encontrar $A A^*$, $A^* A$
2. Encontrar los autovalores/vectores de estas dos matrices
3. Los $\sigma_i$ son $\sqrt{\lambda_i^2}$ donde $\lambda_i^2$ son los autovalores de $A^*A$ o $A A^*$.
4. Los autovectores de $A A^*$ son las columnas de $U$
 Los autovectores de $A^* A$ son las columnas de $V$

Ojoooo.  Establezca dos criterios
1. Los valores singulares son positivos o 0
2. Los valores singulares se ordenan de mayor a menor y los vectores correspondientes ($u_i, v_i$) se ordenan en ese orden.

**Solucion**:
1. Encontremos $A A^*$

$$A A^* = \begin{pmatrix}  1 & 0 & 3 \\ 1 & 2 & 4\end{pmatrix}
\begin{pmatrix} 1 & 1 \\ 0 &2 \\ 3 & 4 \end{pmatrix} =
\begin{pmatrix} 10 & 13 \\ 13 & 21 \end{pmatrix}  $$

Los autovalores de $ A A^*$ satisfacen el polinomio caracteristico $p(\lambda) = \det ( A A^* - \lambda I)$. Estos son (trabajo no hecho en clase, el polinomio caractestico es de oden 2)

$$ \lambda_1^2 = \frac12 ( 31 + \sqrt{797}) \approx 29.62  $$
$$ \lambda_2^2 = \frac12 ( 31 - \sqrt{797}) \approx 1.38  $$

Los autovectores normalizados de $A^* A$.
Se encuentra

$$U_1 = \binom{0.55}{0.83} \quad , \quad u_2 = \binom{-0.83}{0.55} $$

Ahora la matriz $A^* A$

$$A^* A = \begin{pmatrix}
1 & 1 \\ 0 & 2 \\ 3 & 4
\end{pmatrix}
\begin{pmatrix}
1 & 0 & 3 \\ 1 & 2 & 4
\end{pmatrix}
=
\begin{pmatrix}
2 & 2 & 7 \\ 2& 4 & 8 \\ 7 & 8 & 25
\end{pmatrix} $$
Los autovalores son los mismos de arriba mas un autovalor $\lambda_3=0$

Los autovectores, normalizados

$$V_1 = \begin{pmatrix} 0.25 \\ 0.31 \\ 0.92 \end{pmatrix}  \quad , \quad
V_2 = \begin{pmatrix} -0.24\\ 0.94 \\ -0.24 \end{pmatrix}   \quad , \quad
V_3 = \begin{pmatrix} 0.92 \\ -0.24 \\ 0.31 \end{pmatrix}  $$

Los sigmas, las raices cuadradas de los $\lambda_i^2$

$$\sigma_1 = \sqrt{\lambda_l^2} = \sqrt{29.62} \approx 5.44 $$
$$\sigma_2 = \sqrt{\lambda_2^2} = \sqrt{1.38} \approx 1.17 $$

El resultado de las descomposicion es

$$A = U \Sigma V^T =
\begin{pmatrix}
0.55 & -0.83  \\ 0.83 & 0.55
\end{pmatrix}
\begin{pmatrix}
5.44 & 0 & 0 \\ 0 & 1.17 & 0
\end{pmatrix}
\begin{pmatrix}
0.25 & 0.31 & 0.92 \\
-0.24 & 0.94 & -0.24 \\
-0.94 & -0.16 & 0.31
\end{pmatrix}
 $$
Se deja como ejercicio verifcar este triple producto produce $A$ (con algun error).












In [1]:
import numpy as np

U = np.array([[0.55, -0.83], [0.83, 0.55]])
Sigma = np.array([[5.44, 0, 0], [0, 1.17, 0]])
V_T = np.array([[0.25, 0.31, 0.92], [-0.24, 0.94, -0.24], [-0.94, -0.16, 0.31]])


result = np.dot(np.dot(U, Sigma),V_T)
print(result)

[[0.981064 0.014686 2.985704]
 [0.97436  2.004602 3.999544]]


In [2]:
# preguntemmosle el SVD de A
A =np.array ( [[ 1,0,3],[1,2,4]])

# find the SVD (Singular Value Decomposition of A)
U, Sigma, VT = np.linalg.svd(A)
print(U)
print(Sigma)
print(VT)


[[-0.552431   -0.83355863]
 [-0.83355863  0.552431  ]]
[5.44202115 1.17660775]
[[-0.25468288 -0.30634156 -0.91721943]
 [-0.23893064  0.93902322 -0.2472803 ]
 [-0.93704257 -0.15617376  0.31234752]]


Hay muchas interpretaciones de SVD. Por ejemplo si se tiene un cuerpo (coordenadas) el cuerpo puede sufrir (sin transladar) el SVD hace lo siguiente

$$ y = Ax = U \Sigma V^T x $$
el cuerpo es todos los datos en $x$.
1. $V^T x$, toma el cuerpo $x$ y le hace una transformacion ortogonal. Rotacion, o un flip (reflexion) o una combinacion de ambos.

2. $\Sigma V^T x$
Esto toma el resultado de $V^T x$ y lo deforma a lo largo de los ejes principales, estirandolo o comprimiendolo o desapareciendo dimensiones (aplastandolo como en los dibjuos animados).

3. $Ax = U \Sigma V^T$
es una ultima transformacio ortogona: rotacion, o un flip, o una combinacion de ambos.



**Definicion 2.3.1** (condition number, numero de condicion). Al valor

$$ \kappa = \frac{\sigma_1}{\sigma_n} $$
se la llama **numero de condicion**. Este numero es muy importante e indica la estababilidad de un sistema lineal. De hecho si $\sigma_n=0$ el numero de condicion es  infinito y esto quiere decir que la matriz $A$ no tiene inversa.
Si el numero de condicion es muy grande $\lambda_n \ll 1$, entonces el sistema
$Ax=b$ es inestable y cambios muy pequenos en los datos $b$, puede producir cambios muy grandes en la solucion $x$.

## El cociente de Rayliegh.
Se usa en PCA como lo explicare mas adelante.
**Definicion 2.3.2**(Cociente de Rayleigh)
Sea $A$ una matriz auto-adjunta el **cociente de Raylegih** de $A$ se define como

$$R(A, x) = \frac{x^* A x}{x^* x} = \frac{\langle x,  A x \rangle }{\| x \|^2}= \frac{\langle Ax, x \rangle }{ \| x \| } $$

Tambien, se puede usar que $u=x/\| x\|$ entonces

$$ R(A,x) = \frac{x^*}{\| x \| } A \frac{x}{\| x \|}= u^* A u $$
donde $\| u \|= 1$ (esfera de radio 1).



**Teorema 2.3.2**: (cociente de Rayleigh): El mas grande autovalor de $A$ (autoadjunta) corresponde con el maximo valor de los cocientes de Rayleigh de la matriz $A$..

**Prueba**: Asuma que $u \in \mathbb{C}^n$ es un vector unitario. Cada vector del espacio se puede escribir como una combinacion lineal de los vectores base (ortogonales, autovectores de $A$) $\{ u_1, u_2, \cdots, u_n \}$
de forma que

$$ u= \sum_{i=1}^n \alpha_i u_i $$
donde $ \| u \| = \sqrt{ \sum_{i=1}^n {\alpha_i}^2}= 1 $

Por definicion de cociente de Rayleigh  y aplicando la distributiva


$$R(A, u) = u^* A u = \sum_{i=1}^n \sum_{j=1}^n \overline{\alpha_i} \alpha_j u_i^* A u_j $$

Ahoora como cada $u_k$ es autovector de $A$ con autovalor $\lambda_k$ entonces

$$ u_i^* A u_j = u_i^* ( \lambda_j u_j) = \lambda_j u_i^* u_j = \lambda_j \delta_{ij}  $$
de forma que

$$R(A, u) = \sum_{i=1}^n \sum_{j=1}^n \overline{\alpha_i} \alpha_j u_i^* A u_j = \sum_{i=1}^n | \alpha_i |^2 \lambda_i = \sum_{j=1}^n | \alpha_j |^2 \lambda_j  \tag{4} $$

Algunos hechos
* La suma anterior es un promedio ponderado.
* $\lambda_1$ es el mas grande de todos autovalores (asi los escojo, por capricho mio)
* El cociente de Rayleigh mas grande es cuando escojo

$$u=(1, 0, 0, \cdots, 0) $$
por que le da mayor peso al primero $\lambda_1$ y ningun peso a los demas.
De forma que

El mas grande de los cocientes de Rayleigh es $\lambda_1$.

Si $\lambda_2$ es el mas grande de los autovalores, yo escojo
$u=(0,1,0 \cdots , 0)$ y la ecuacion (4) produce


$$R(A, u) = \lambda_2  $$
En las notas de clase hay otra forma al final para probar esto. Lo dejo de lectura.

**Teorema 2.3.3.** (Cholesky). Si $A$ es positiva definida y auto-auto adjunta, entonces exiten $L$ tal que

$$A = L L^* $$
Si $L$ es autoadjunta entonce $L=L^*$ y $A=L^2$ de forma que
$L$ es la raiz cuadrada de $A$. No lo usaremos en el curso.

Tarea de lectura: Leer la seccion 2.4 de las notas de clase:
Applications of eigenvalues and eigenvectors.

# Proxima clase: Calculo matricial.