$\newcommand{\bmx}{\large \boldsymbol{x} \normalsize}$
$\newcommand{\bmc}{\large \boldsymbol{c} \normalsize}$
$\newcommand{\bmy}{\large \boldsymbol{y} \normalsize}$
$\newcommand{\bmb}{\large \boldsymbol{b} \normalsize}$

# Introduccion:
Existen varios metodos para analisis numerico de ecuaciones difereniales parciales.

* Diferencias finitas
* Volumenes finitos
* metodos espectrales
* etc.

El curso se centra en diferencias finitas para las ecuaciones de calor, onda y Laplace/Poisson.

Lo mas importante mas del 99.99999% de ecuaciones PDE (Partial Differential Equations) no tienen solucion analitica. Y la unica esperanza es la solucion numerica.

Nuericamente, las ecuaciones que resolvemos aca son **lineales**. Se necesita resolver problemas de la forma $Ax=b$. Las tecnica de Eliminacion de Gauss son muy limitadas para problemas grandes (matrices de 1000x1000) y entonces se necesitan metodos iterativos (buenos para matrices esparsas, con muchos cero). Los mas famosos son:

* Gauss Seidel
* Jacobi
* Over-relaxation.

En esta primera parte del curso los vemos con mas detalle que el que se ensena en metodos numericos I.
Esto motiva el primer capitulo:


#Tecnicas Iterativas en Algebra Matricial.
Los metodos iterativos son de la forma



$\newcommand{\bmx}{\large \boldsymbol{x} \normalsize}$
$\bmx_i = T \bmx_{i-1} + \bmc$

En esta ecuacion
* $\bmx$ es un vector en $\mathbb{R}^n$
* $T$ es una transformacion lineal (una matrix).
* $\bmx_{i-1}$ corresponde al tiempo anterior (ayer)
* $\bmx_{i}$ hoy (hoy).

La idea es que este sistema se puede pensar de la siguiente forma

$$\bmx_1 = T \bmx_0 + \bmc  $$
$$\bmx_2 = T \bmx_1 + \bmc  $$
$$ \vdots $$
$$ \bmx_n = T \bmx_{n-1} + \bmc $$.

La idea es que la secuencia de soluciones

$$S = \{ \bmx_0, \bmx_1, \cdots, \bmx_n, \cdots \}  $$
converja? que es eso. Es que exista un limite

$$\lim_{i \to \infty}  \bmx_{i} = \bmx$$
Si eso fuese asi tendriamos que para este $\bmx$

$$\bmx = T \bmx + \bmc  $$
Esta una ecuacion de **punto fijo**. Si

$$S \bmx = T \bmx + \bmc  $$
$$ S \bmx = \bmx$$.
Este punto fijo, a diferencia de su curso en Metodos I es para un operador lineal $S$.

Antes de estudiar en forma estos temos debemos definir algunos conceptos importantes del algebra lineal:
* norma
* metrica (distancia entre dos puntos)
* autovalores/autovectores
* matriz convergente
* matriz positiva definida
* el circulo de Gershgoric

## Conceptos basicos de algebra lineal.
Queremos, para poder estimar el **error** debemos estimar la distancia entre dos puntos. Por ejemplo en $\mathbb{R}^2$
Si $(x_1, x_2), (y_1, y_1) \in \mathbb{R}^2$ entonce la distancia (**metrica**) Euclidiana, Pitagorica

$$d[ (x_1, x_2), (y_1, y_2) = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2}$$
Se puede generalizar a $\mathbb{R}^n$, o sea si
$$(x_1, x_2, \cdots, x_n) \in \mathbb{R}^n $$
$$(y_1, y_2, \cdots, y_n) \in \mathbb{R}^n $$
Entonces

$$d[(x_1, x_2, \cdots, x_n), (y_1, y_2, \cdots, y_n) =
\sqrt{\sum_{i=1}^n (x_i-y_i)^2} $$

**Definicion**(norma $\| . \|$).
En abstracto, la norma de un vector se define con 3 postulados (axiomas).

1. **Positividad**:
$$\|\bmx \| \ge 0 \quad \text{y que }  \| \bmx \|=0 \quad \text{si y solo si}  \quad \bmx = 0   $$

2. **Homgeneidad**:
Para cualquier esalar $\alpha \in \mathbb{R}$, o $\mathbb{C}$.
$$ \| \alpha \bmx \| = | \alpha | \| \bmx \| $$

3. **Desigualdad triangular**
$$\| \bmx + \bmy \| \le \| \bmx \| + | \bmy \|.  $$

Hay muchas cosas que son normas. Aca nos centramos en algunas particulares.

Asumimos $\bmx \in \mathbb{R}^n$
* La norma $p$, $\ell_p$

$$\ell_p(\bmx) = \| \bmx \|_p = \left ( \sum_{i=1}^n |x_i|^p  \right )^{1/p} $$

Ejemplos

*
    * $p=1$,
$$\ell_1 = \| \bmx \|_1  = \sum_{i=1}^n | x_i |$$
A esta norma se le conoce como la del **taxista**. (Manhattan Norm).
Ejemplo
$$\left \| \binom{-2}{5} \right \|_1 = |-2| + |5| = 7. $$

    * $p=2$: Euclidiana
$$\ell_2(\bmx) = \| \bmx \|_2 = \sqrt{\sum_{i=1}^n | x_i^2|} $$
    * $p=\infty$:
$$\ell_\infty(\bmx)= \| \bmx \|_{\infty} = \max | x_i | $$
Las normas $p$ se definen para $p \ge 1$. Que pasa si $p<1$?
Ejercicio, dibujara "esferas" con la norma $p$.

Tarea:
Pruebe que

$$\lim_{p \to \infty} \ell_p = \ell_\infty. $$

La norma induce una distancia o metrica.

Por ejemplo, si $\bmx, \bmy \in \mathbb{R}^n$

$$d(\bmx , \bmy) = \ell_p(\bmx, \bmy) = \| \bmx - \bmy\|_p =
\left ( \sum_{i=1}^n | x_i - y_i |^p \right )^{1/p} $$

Las matrices tambien tienen normas.
[Wikipedia](https://en.wikipedia.org/wiki/Matrix_norm) muestra con detalle la definicion de normas matriciales con ejemplos.

Veamos normas matriciales **inducidas** por las normas vectoriales.








** Definicion (cota superior). Decimos que $y$ es cota superior de $A$ (un conjunto de los reales) si
$y \ge x$, $\forall x \in $A$.

Por ejemplo $A= \{ 1, 3, 5\}$ .
Entonces 6 es cota superior de $A$
Entonces 5 es cota superior de $A$. 5 Es la mayor. Es el SUP.
Si un conjunto es cerrado el sup es el maximo.


**Definicion (sup)**:

Entenemos que es el maximo y minimo. Pero ahora queremos definir el **sup** y el **inf**.
El sup (supremum) tambien en ingles se llama lup: Least Uppper Bound). Es la cota superior mas pequenha.

Ejemplos
Sea
$A=[0,1]$. El numero 2 es cota superior de $A$. Pero el 1.5 es mas pequenho que 2, y el 1.1 mas pequenho que 1.5. Pero 1 es la cota superior mas mequenha de todas. Por que si $1$ le resta un $\epsilon$, $1- \epsilon$ y no es cota, existe $y$
tal que $1 - \epsilon < y$, $y \in A$.
Matematicamente $x$ es el **sup** de $A$



1. si $x \ge y$ $\forall y \in A$. (cota superior quiere decir que esta por encima)

2. Para cualquier $\epsilon > 0$, $x -\epsilon < y$ para algun $y \in A$.
Ejemplo. $A=[0,1]$. Sea $\epsilon=0.1$.
$1- \epsilon = 0.9$. Puedo enconntrar $y=0.99 > 1- \epsilon =0.9$ $y$.

Otro ejemplo
$A=(0,1)$. Es numero 1 **no es maximo**. $1 \in A$. Pero el el sup. Por que es cota superior y la mas pequena de todas.

**Definicion (inf=infimum)**: El infimum (glb: Greatest lower bound). La mas grande de todas las cotas inferiores.

$x = \inf (A)$ si
1. Es cota inferior. Es decir $x \le y$, $\forall y \in A$
2. Si yo le sumo cualquier numero positivo a $x$ entonces va existir un $y \in A$ tal que $x + \epsilon \le y$.


1. **Normas matriciales inducidas por normas de vectores**.
Asuma $A \in \mathbb{R}^{m \times n}$ como operador en un espacio vectorial de vectores $\bmx \in \mathbb{R}^n$. Se define la norma de la matriz $A$ como sigue

$$\| A \| = \sup \{ \| A \bmx \| : \| \bmx \| = 1   \}= \sup \left \{  \frac{\| A \bmx \|}{\| \bmx \|} \right \} $$

Donde $\| \bmx \|$ y $\| A \bmx \|$ son las normas de los vectores en sus respectivos espacios $\mathbb{R}^n$ y $\mathbb{R}^m$.

No necesariamente las matrices deben ser cuadradas para tener una norma. Asumamos $A \in \mathbb{R}^{m \times n}$ donde
$n$ no necesariamente es igual a $n$.
2. **Nomas $p$ de una matriz**.
    1.
$p=1$
$$\| A \|_1 = \max_{1 \le j \le n} \sum_{i=1}^m | a_{ij} | $$
    2.
    *
$p=2$
$$\| A \|_2 = \sigma_{\max}(A) $$
donde $\sigma$ son los valores caracteristicos de $A$.
Es decir los autovalores de $A^T A$. En un momento definimos autovalores.

   3.
    
$p=\infty$
$$\| A \|_{\infty} =  \max_{1 \le i \le m} \sum_{j=1}^n | a_{ij}| $$


**Definicion** (Frobenius). La norma Frobenius es como la extension de la norma 2  a matrices

$$\| A \|_F = \sqrt { \sum_{i=1}^m \sum_{j=1}^n | a_{ij} |^2} $$

Dejamos como ejercicio probar que para $p=1,2, \infty$, tenemos que

$$\| A \|_p = \sup \{  \| A \bmx \|_p  : \| \bmx \| = 1 \} $$

**Definicion de autovalor/vector**: Tambien los llaman valores caracteristicos y vectores caracteristicos.
Si existe un vector $\bmx \ne 0$ y un escalar (real o complejos) $\lambda$ tales que

$$A \bmx = \lambda \bmx $$
Decimos que $\bmx$ es autovector (o vector propio) de la matriz $A$ y que $\lambda$ es auto-valor o valor propio de $A$.

No todos los vectores son autovectores. Veamos un contraejemplo

$$A = \begin{pmatrix} 1 & 2 \\ 3 & - 1 \end{pmatrix} \tag{1} $$
$$\bmx = \binom{2}{1} $$.
Entonces

$$A \bmx = \binom{4}{5} $$
y $\binom{4}{5}$ no es un multiplo de $\binom{2}{1}$

Para entender un poco el significado de autovalor/vector
[Wikipedia](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors)
ver graficas animadas y la Gioconda (Monalisa).

Algoritmo para encontrar los autovalores/vectores.

$$A \bmx = \lambda \bmx $$
$$A \bmx - \lambda \bmx =0$$
$$(A - \lambda I) x = 0 $$
como $\bmx \ne 0$ entonces el determinande de la matriz $A - \lambda I$ es 0 (algebra lineal).

$$p(\lambda) = \det(A - \lambda I) = 0. $$
El algoritmo es encontrar  las raices del polinomio caracteristico $p(\lambda) =0$ y con esas raices haciendo eliminacion Gaussiana encontrar $\bmx$. Son infinitos. De hecho  si $\bmx$ es autovector entonce $c \bmx$ tambien lo es. Veamos

Si $\bmx$ es autovector entonces

$$A \bmx = \lambda \bmx $$
ahora llame $\bmy = c \bmx$, $c \ne 0$.

$$c A \bmx = \lambda c \bmx $$
$$ A c \bmx = \lambda c \bmx $$
$$ A \bmy = \lambda \bmy $$

**Ejemplo**: Encuentre los autovalores/vectores de la matriz $A$ en (1).

El algoritmo para los autovalores es hallar las raices del polinomio caracteristico $p(\lambda) = \det (A - \lambda I)$.

$$
\det ( A - \lambda I) = \det
\left [
\begin{pmatrix}
1 & 2 \\
3 & - 1
\end{pmatrix}
- \begin{pmatrix}
\lambda & 0 \\ 0 & \lambda)
\end{pmatrix}
\right ] \\
\det
\begin{pmatrix}
1 - \lambda & 2 \\ 3 & -1 - \lambda
\end{pmatrix} \\
(1-\lambda)(-1 -\lambda) - 6 \\
\lambda^2 -1 - 6 \\
\lambda^2 - 7 = 0
$$
De forma que $\lambda = \pm \sqrt{7}$
Como hallamos los autovectores?
Volvemos a la ecuacion $(A - \lambda I) \bmx = 0$

Es decir
Consideremos por ahora $\lambda=\sqrt{7}$

$$(A - \lambda I) \bmx = 0 \\ $$
$$ \begin{pmatrix}
1 - \sqrt{7} & 2 \\ 3 & -1 - \sqrt{7}
\end{pmatrix} \binom{x_1}{x_2} = 0 $$



$$(1 - \sqrt{7} )x_1 + 2 x_2 = 0 $$
$$3 x_1 -(1 - \sqrt{7})x_2 = 0$$
Asumir que $x_1=1$ halla $x_2$

$$(1 - \sqrt{7} )1 + 2 x_2 = 0 $$
de aca que

$$x_2 = \frac{-1 + \sqrt{7}}{2} $$
Todos los vectores de la forma

$$\binom{1}{ \frac{-1 + \sqrt{7}}{2}} $$
son autovectores.

In [2]:
import numpy as np
A = np.array([[1,2],[3,-1]])
np.linalg.eig(A)

EigResult(eigenvalues=array([ 2.64575131, -2.64575131]), eigenvectors=array([[ 0.7721779 , -0.48096517],
       [ 0.6354064 ,  0.8767397 ]]))

In [3]:
np.sqrt(7)

np.float64(2.6457513110645907)

In [4]:
-0.48096517/0.7721779

-0.622868344198921

In [7]:
a= (-1 + np.sqrt(7))/2

In [8]:
a*0.6354064

np.float64(0.5228604579294159)

**Definicion matriz positiva definida**
La matriz $A$ es positiva definida si para todo $\bmx \in \mathbb{C}^n$ $x^* A x > 0$, donde $x^*$ es el transpuesto conjugado de $\bmx$. Por ejemplo si
$$\bmx = \binom{1 + 2 \mathrm{i}}{3 + 4 \mathrm{i}} $$
$$\bmx^* = (1 - 2 \mathrm{i}  \quad 3 - 4 \mathrm{i})$$
**Definicion matriz negativa definida**
La matriz $A$ es positiva definida si para todo $\bmx \in \mathbb{C}^n$ $x^* A x < 0$, donde $x^*$ es el transpuesto conjugado de $\bmx$. Por ejemplo si
$$\bmx = \binom{1 + 2 \mathrm{i}}{3 + 4 \mathrm{i}} $$

Se puede probar (ejercicio) que
si $A$ es positiva definida  entonces todos sus autovalores son positivos.

si $A$ es negativa definida  entonces todos sus autovalores son negativos. (ejercicio)

**Definicion diagonal estrictamentedominante**: Una matriz $A$ es  diagonalmente dominante por filas si

$$| a_{ii} | \ge \sum_{j=1; j \ne i}^n  | a_{ij}|  $$

Ejemplo
$$ A =\begin{pmatrix} 10 & 4 & 2 \\ 0 & 5 & 1 \\ 3 & 2 & 6 \end{pmatrix}  $$

como
$$10 \ge 4 +2  \quad \text{y} \quad 5 \ge 0 + 1 \quad \text{y} \quad 6 \ge 3 + 2  $$
Entonces $A$ es diagonalmente dominante por filas


**Definicion diagonalmente dominante por columnas**
En este caso

$$| a_{jj} | \ge \sum_{i=1, i \ne j}^n |a_{ij}| $$
En el ejemplo anterior $A$ no es diagonalmente dominante por columnas pues la segunda columna presenta lo siguiente.
* La diagonal es 5
* La suma de las otras dos es: $4 + 2 = 6$ y

$$ 6 \nless 5 $$

Ojo, cuestion de lenguaje. POdemos usar la palabra **estrictamente** y cambiar todos los mayor o igual $\ge$ por $>$.

Ya tenemos los elementos para volver a la norma 2 de una matriz.
Dijimos que la norma $2$ esta dada por el maximo de los valores singulares $\sigma_i$ donde $\sigma_i$ es la raiz cuadrada del autovalor de la matriz $A^* A$ donde $A^*$ es la transpuesta conjugada.


Ejemplo:

$$ A= \begin{pmatrix} 5 & 3 \\ 4 & - 1 \end{pmatrix}$$
$$ A^T= \begin{pmatrix} 5 & 4 \\ 3 & - 1 \end{pmatrix}$$

$$A^T A = \begin{pmatrix} 41 & 11 \\ 11 & 10 \end{pmatrix} $$




In [15]:
A = np.array([[41,17],[17,17]])
np.sqrt(np.linalg.eigvals(A))

array([7.0575245, 2.8620531])

In [ ]:
np.singular

In [13]:
import numpy as np

A = np.array([[5, 3], [4, -1]])
norm_2 = np.linalg.norm(A, ord=2)
print(norm_2)

6.671325041455274


In [16]:
A = np.array([[5,3],[4,-1]])

In [18]:
np.linalg.svdvals(A)

array([6.67132504, 2.54821942])

In [19]:
A

array([[ 5,  3],
       [ 4, -1]])

In [21]:
C = np.matmul(np.transpose(A),A)

In [22]:
np.sqrt(np.linalg.eigvals(C))

array([6.67132504, 2.54821942])

In [23]:
C

array([[41, 11],
       [11, 10]])