```
def casa(self, filtro):
  return filtro in self.memo or filtro in self.etiqueta
```



# Polimorfismo:
Varias formas. Las tecnicas que contemplamos son dos.

1. Override (ya vimos algo pero la extendemos un poco.
2. Overload (no hemos visto nada esto).


## Override revisited (volvemos a visitarla)
El ejemplo que vemos, que es clasico, es de la forma como se mueven los animales. Veamos la implementacion.

In [ ]:
class Animal:

    def __init__(self, name):
        self.name = name
        return

    def move(self):
        print("I am an %s and I am moving  \n"%self.name)
        return


class Fish(Animal):

    def move(self):
        print(f"I am a {self.name} and I swim")
        return

class Snake(Animal):

    def move(self):
        print(f"I am a {self.name} and I crawl")
        return

myFish = Fish("fish")
myFish.__dict__

{'name': 'fish'}

In [ ]:
myFish.move()

I am a fish and I swim


In [ ]:
mySnake = Snake("snake")
mySnake.move()

I am a snake and I crawl


In [ ]:
myAnimal = Animal("animal")
myAnimal.__dict__

{'name': 'animal'}

In [ ]:
myAnimal.move()

I am an animal am moving 



In [ ]:
coco = Snake("snake")
coco.move()

I am a snake and I crawl


In [ ]:
coco2 = Snake("fish")

In [ ]:
coco2.move()

I am a fish and I crawl


## Overloading (sobrecarga)
Vemos dos tipos de overloading.

### Function Overloading: sobrecarga
en una funcion. Este concepto trabaja bien en Java, C++ pero **no** en Python como lo vamos a ver.
"Hay que darle la vuelta", "walk around".


In [ ]:
class Sum:

    def __init__(self):
        return


    def sum(self, x, y):
        return x + y

    # En override el signature se conserva, en function overload el signature cambia
    def sum(self, x, y, z):
        return x+y+z

a = Sum()
print(a.sum(2,3,4))

9


In [ ]:
print(a.sum(2,3))

TypeError: ignored

In [ ]:
# en python realmente pasa es "overwrite" (sobreescribe con el ultimo)
class Sum:

    def __init__(self):
        return


    # En override el signature se conserva, en function overload el signature cambia
    def sum(self, x, y, z):
        return x+y+z

    def sum(self, x, y):
        return x + y


a = Sum()
print(a.sum(2,3,4))

TypeError: ignored

In [ ]:
print(a.sum(2,3))

5


Hay una forma de "darle la vuelta" al problema. Para esto necesitamos usar el "if" statement

In [ ]:
# veamos un ejemplo donde se sobrecarga el metodo __init__()
class Student():

    # first __init__()
    def __init__(self):  # no tiene parametros
        self.name = "Jack"
        self.score = 0
        return

    # second __init__
    def __init__(self, name, score):
        self.name = name
        if (score < 0 ):
            print("invalid score. It should be a positive number")
        else:
            self.score = score
        return

st = Student()




TypeError: ignored

In [ ]:
# duck typing
class Sum:

    def __init__(self):
        return


    # En override el signature se conserva, en function overload el signature cambia
    def sum(self, x, y, z=0):
        return x+y+z

a = Sum()
print(a.sum(2,3))

5


In [ ]:
import numpy as np
x = np.array([[1,3],[-2,0]])
y = np.array([[0,7],[-2,-5]])
print(x)
print(y)

[[ 1  3]
 [-2  0]]
[[ 0  7]
 [-2 -5]]


In [ ]:
z=0
print(a.sum(x,y,z))

[[ 1 10]
 [-4 -5]]


In [ ]:
x=3+2j
y=3-2j
print(a.sum(x,y))

(6+0j)


In [ ]:
x="hola  "
y="como estas"
print(a.sum(x,y))

hola  como estas


In [ ]:
x

array([[ 1,  3],
       [-2,  0]])

In [ ]:
x+0

array([[ 1,  3],
       [-2,  0]])

In [ ]:
x+2 #matrix mas escalar. El matrix donde se suman todos los escalares

array([[3, 5],
       [0, 2]])

In [ ]:
a="hola"
b=2
a+b

TypeError: ignored

In [ ]:
# como le damos la vuelta a la clase Student
# una forma puede user usando los parametros de default.
class Student2():

    # first __init__
    def __init__(self, *args): # variable arguments
        if len(args)==0:
            self.name = "Jack"
            self.score = 0
        if len(args)==2:
            self.name=args[0]
            if args[1] < 0:
                print("scores should be positive!")
            else:
                self.score = args[1]
        return

    def showData(self):
        print("name=%s, score=%d\n"%(self.name, self.score))

st = Student2()
st.showData()

name=Jack, score=0



In [ ]:
st2 = Student2("George", 4)
st2.showData()

name=George, score=4



In [ ]:
# sume una cadena de numeros

In [ ]:
# en python realmente pasa es "overwrite" (sobreescribe con el ultimo)
class Sum:

    def __init__(self):
        return


    # En override el signature se conserva, en function overload el signature cambia
    def sum(self, *args):
        n = len(args)

        s=0
        for i in range(n):
            s += args[i]

        print("la suma es",s)
        return



a = Sum()
a.sum(2,3,4)

la suma es 9


In [ ]:
a.sum(5,3,5,9,9,10)

la suma es 41


In [ ]:
st3 = Student2("Michael", -1)

scores should be positive!


## Operator overloading.
Los operadores,  por ejemplo, +, -, *, %, etc se pueden sobrecargar. El "duck typing" funciona bien y es una sobrecarga para muchos tipos. Pero que pasa si tengo libros y quiero sobre cargar el simbolo "+" para que sume las paginas. De forma que diga
LibroA + libroB= n
donde n es el numero de paginas de A + el numero de paginas de B.
Obvio que Python no sabe esto. Aca no hay "duck typing".


El overloading the "+" se hace con la funcion ```__add__()```
y el de multiplicacion es ```__mul__()```

In [ ]:
a=5
print(dir(a))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [ ]:
# python tiene suma y multiplicacion de complejos, pero nosotros le vamos
# a hacer el "overloading", asumiendo que no sabemos
class Complex:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, otro): # add point to a point (x,y)
        x = self.x + otro.x
        y = self.y + otro.y
        return (x,y)

    def __mul__(self, otro): # multiplica el punto (x,y) por otro
        x = self.x*otro.x - self.y*otro.y
        y = self.y*otro.x + self.x*otro.y
        return (x,y)



In [ ]:
a = Complex(5,2)
b = Complex(-1,3)
print(a.__dict__)
print(b.__dict__)

{'x': 5, 'y': 2}
{'x': -1, 'y': 3}


In [ ]:
print("la suma a+b = ", a+b)
print("el producto a*b = ", a*b)

la suma a+b =  (4, 5)
el producto a*b =  (-11, 13)


In [ ]:
# python maneja esto naturalmente en los complejos
a = 5 + 2j
b = -1 + 3j
a*b

(-11+13j)

# Proxima clase Abstraccion