Para hoy tenemos do temas fundamentales.

* El teorema espectral de operatores autoadjuntos
* El teorema fundamental SVD: Singular Value Decomposition.


## Teorema espectral.

**Lema**:  Para caa espacio invariante $W \ne \{ 0 \}$ de una matriz cuadrada $A$, existe (siempre) in autopar $\lambda, x$.

prueba: Com $W$ es finito dimensional tiene una base
$\{x_1, x_2, \cdots, x_k \}$ donde $k$ es la dimension de $W$.
Recuerden que $A W \subset W$. Sea $x \in W$, entonces $Ax \in W$.
$x=\sum_{i=1}^k \alpha_i x_i$, para $x \ne 0$. Puedo escribir

$$A x_i = \sum_{j=1}^k  \beta_{ji} x_j \quad (1) $$

Queremos probar que existe $\lambda$ tal que $A x - \lambda x=0$ para $x \in W$. 
Es decir:

$$ A x = \sum_{i=1}^k \alpha_i A x_i = \lambda \sum_{i=1}^k \alpha_i x_i $$

Restamos la izquierda menos centro,

\begin{eqnarray}
\sum_{i=1}^k \alpha_i A x_i - \lambda \sum_{i=1}^k \alpha_i x_i &=&0  \quad \text{restando izquierda de centro} \\
\sum_{i=1}^k \alpha_i \sum_{j=1}^k \beta_{ji} x_j - \lambda \sum_{i=1}^k \alpha_i x_i &=&0  \quad \text{usando ecuacion (2)} \\
\sum_{i=1}^k \alpha_i \left ( \sum_{j=1}^k \beta_{ji} x_j - \lambda x_i \right ) &=& 0  \quad \text{factorizamos la suma} \\
\sum_{i=1}^k \alpha_i \left ( \sum_{j=1}^k \beta_{ji} x_j - \lambda \sum_{j=1}^k x_j \delta_{ij} \right ) &=& 0 \text{truco del delta   } x_i=\sum_{j=1}^k \delta_{ij} x_j \\
\sum_{i=1}^k \alpha_i \left (  \sum_{j=1}^k \beta_{ij} x_j - \lambda \delta_{ij} x_j  \right ) &=& 0   \quad \text{recogiendo la segunda suma} \\
 \sum_{j=1}^k \left ( \sum_{i=1}^k \alpha_j (\beta_{ij} - \lambda \delta_{ij}) \right ) x_j &=& 0 
\end{eqnarray}

En este punto vemos que los $x_j$ tienen unos pesos en la combinacion lineal los cuales producen 0. Y como los $x_j$ son **linealmente independintes** , entonces los coeficientes de $x_j$ sosn todos cero.

Es decir:

\begin{eqnarray}
 \sum_{i=1}^k \alpha_j (\beta_{ij} - \lambda \delta_{ij}) = 0
\end{eqnarray}

Esto de forma matricial es: $(B-\lambda I) \alpha = 0$. 
Pero hay un teorema que dice que $B$ tiene que tener por lo menos un autovalor, y lo tiene yes $\lambda$. 

Por lo tanto cada subsepacio de $W$ invariante de $A$ tiene por lo menos una autovector/valor. 

### Teorema espectral para matrices adjuntas.
Sea $A$ una matriz $n \times n$ autoadjunta, entonces existe una
base base ortonormal.

$$\{ x_1, x_2, \cdots, x_n \} $$
para la cual la matriz $Q$  (columnas de esta base) satisface la relacion

$$ A = Q \Lambda Q^* $$
donde $\Lambda$ es una matriz diagonal con los autovalores de $A$.
Es decir cada entrada de la matriz de $A$ es $\delta_{ij} \lambda_j=\lambda_i$. 

**Prueba:**  Por induccion.

* Se prueba para $k=1$
* Se asume que es valido para $k$ y se prueba para $k+1$.
Yo llamo a estas pruebas, el efecto domino. 

**Prueba**: 
*   k=1:  ($k$ es la dimensio de la matriz $A$)
Si $k$, La base de esta matriz es $\{ x_1 \}$, $ x_1 \ne 0$. y
esta base se puede normalizar $x_1/x_1=1$, $\{ 1 \}$. 

$3 = (1)(3)(1)$. Por defecto y vacuidad $\{1 \}$ es otonormal.

* Asumimos que el teorema es valido para $k$ y probamos que es valido para $k+1$.
Valido para $k$: Existen $k$ vectores $\{ x_1, x_2, \cdots , x_k \}$ que con ortogonales (dos a dos) y tales que $A x_i = \lambda x_i$.
Debemos prabar que existe otro $x_{k+1}$ que es ortogonal a todos los demas. 
Buscamos el complemento ortogonal del generado de los vectores vasos
$\langle x_1, x_2, \cdots, x_k \rangle $, llamemoslo $W$

$$ W = \langle x_1, x_2, \cdots, x_k \rangle^{\perp}$$
Por definicion el **complento ortogonal** de un espacio $V$ es el conjunto de todos los $y$ tales que $\langle y, x \rangle = 0$, para todo $x \in V$.

Vamos a probar que $W$ es invariante para $A$ y por el teorema anterior tiene por lo mentos un autovalor/vector que no esta en los anteriores. 

ES decir probalmos que si $y\in AW$, entonces $y \in W$.

Sea $y \in AW$, $y=Ax$, $x \in W$.  Para cada $x_i , i=1,2, , k$

$$ \langle y, x_i \rangle = \langle Ax, x_i \rangle = \langle x, A^* x_i \rangle = \langle x, A x_i \rangle = \langle x, \lambda_i x_i \rangle = \lambda_i \langle x, x_i \rangle = 0 $$

Es decir $c$ es perpendicular a **todos** $x_i$ y por lo tanto al generado, o sea que $x \in W$. Osea que $W$ es invariante, o sea que
$W$ tiene un autovalor/vector que tienen que ser distintos a los
$\lambda_1, \lambda_2, \cdots , \lambda_k$, $x_1, x_2, \cdots, x_k$
y con esto lo podemos nombrar que autovalor $\lambda_{k+1}$ y autovector $x_{k+1}$.

Listo la prueba por inducccion para la construccion de $n$ autvalores y $n$ autovectores ortogonales, (los autovalores pueden tener repetidos). Los podemos normalizar, $x_i/\| x_i \|$ y esto 
me da una base ortonormal. Nos devolvemos a la clase anterior y

$$A = Q \Lambda Q^* $$




Multiplicando a izquierda por $Q^*$ y a derecha por $Q$

$$ Q^* A Q = \Lambda $$

Vamos a ver algunas aplicaciones interesantes de este teorema.

Habemos de los sistemas quadraticos, en $\mathbb{R}^n$.
Matriz $A$ es $n \times n$

$$\langle Ax, x \rangle = x^T A x =  \sum_{i=1}^n  \sum_{j=1}^n  a_{ij} x_i x_j $$

Como $A$ es simetrica los elementos por fuera la diagonal de $A$ $(n^2 - n)$ estan **acoplados**. $a_{23} x_2 x_3,a_{32} x_3 x_2= 2 a_{23} x_2 x_3$. Vamos a ver como la descomposicion espectral simplifcia el problema.
recuerde $A=

$$x^T A x = x^T Q \Lambda Q^T x $$
Cambio de variable $y=Q^T x$ entonces se convierte en

$$x^T A x = y^T \Lambda y$$
como $\Lambda$ es diagonal se pierde la doble suma si convierte en
$$x^T A x = y^T \Lambda y  = \sum_{i=1}^n \lambda_i y_i^2$$


Teorema para aprender a multiplicar matrices de diversas formas.

Teorema: Sea $A$ una matriz $m \times n$, $B$ una matriz $n \times p$, $x$ un vector en $\mathbb{C}^n$, $\Lambda$ una matriz $n \times p$ diagonal con valores $\lambda_i$ en la diagonal y cero por fuera. entonces

* $$ AB = [AB_1 | AB_2 | \cdots | AB_p]$$
donde $B_i$ son columnas de la matriz $B$.

* $$ Ax = \sum_{j=1}^n x_j A_j$$
donde $A_j$ son columnas de la matriz $A$. Es decir $x \in \mathcal{R}(A)$. 

* Si $p \ge n$.

$$ A \Lambda = [ \lambda_1 A_1 | \lambda_2 A_2 \cdots | \lambda_n A_n | 0 | \cdots | 0  $$
donde agregamos $p-n$ columnas de ceros, Si $n>p$

$$ A \Lambda = [ \lambda_1 A_1 | \lambda_2 A_2 \cdots | \lambda_p A_p] \quad \quad (2) $$

* Si $u_i$ es un vector columna de una matriz $U$, $m \times m$ entonces

$$ U^* b = \begin{pmatrix} u_1^* b \\ u_2^* b \\ \vdots u_m^* b
\end{pmatrix} $$

Nos vemos  las 8: 00 am.

Probemos el primero.
Llamemos $C=AB$, de forma que

$$c_{ij} = \sum_{k=1}^n a_{ik} b_{kj}. $$
Tomoemos la columna $j$ del lado derecho. Y de aca la fila i

$$ (AB_j)_i =   \left ( \sum_{k=1}^n a_{ik} b_{kj} \right )_i $$

Las otras pruebas son **parecidas** y cortas.

Que pasa si todos los autovectores no son ortogonales (el caso de matrices no autoadjuntas) pero son linealmente independientes.

Es decir, sean estos $P_i$ $A$ es $n \times n$

$$ AP_i = \lambda_i P_i $$
En forma matricial (construyendo $P=[P_1 | P_2 | \cdots P_n]$)
Por las propiedades anteriores (2).

$$ AP = P \Lambda$$. 
Como los vectores $P_i$ son linealmente indepndientes, $P$ tiene inversa
y multiplicamos por $P^{-1}$ primero a izquierda y luego a derecha:

$$ P^{-1} A P = P^{-1} P \Lambda $$
a derecha
$$ AP P^{-1} = P \Lambda P^{-1} $$  (como $P P^{-1}=P^{-1} P=I$)

$$ \Lambda = P^{-1} A P $$
$$ A = P \Lambda P^{-1}$$.

Esta es la pruebaa del teorema: Si $A \in \mathbb{C}^{n \times n}$ con $n$  autovectores linealmente indepndientes, entonces
$A=P \Lambda P^{-1}$, $\Lambda = P^{-1} A P$, donde $P$ es la matriz de autovectores (columnas) y $\Lambda$ es una diagonal con autovalores.
A la matriz $A$ se le conoce como **diagonalizable**

Miremos como usar esto para elevar una matriz a una potencia.

Teorema: Si $A$ es diagonalizable, es decir $A=P \Lambda P^{-1}$ con $\Lambda$ diagonal, entonces:

$$ A^k = P \Lambda^K P^{-1}$$.

Probemos por induccion:

* $k=1$. Nada que hacer.
* Asumimos que es valido para $k$ y probamos para $k+1$.

\begin{eqnarray}
A^{k+1} &=& A^k A \quad \text{recursividad de la potencia}  \\
&=& P \Lambda^k P^{-1} P \Lambda P^{-1}  \quad  \text{hipotess} \\
&=& P \Lambda^k (P^{-1} P) \Lambda P^{-1} \quad \text{asociativa} \\
&=& P \Lambda^k \Lambda P  \quad P^{-1} P = P P^{-1} = I  \\
&=& P \Lambda^{k+1} P^{-1}
\end{eqnarray}

Esto prueba el teorema por inducccion. 

No tadas las matrices son diagonalizables, para aqueyas que no se aproxima la diagonalizacion en el teorema de [Jordan](https://en.wikipedia.org/wiki/Jordan_normal_form)  (cuando los autovectores no son linealmente independientes.



Definicion. Una matriz (autoadjunta0 es **positiva definida** si todos sus autovalres son positivos, **negativa definida** si todos los autovalres son negativos, y **no negativa definida** si todos los autovalres son positivos o 0.
Se puede probara que esta definicion es equivalente a:

* Positiva definidad: Para todo $x \in \mathbb{C}^n$, $x^T A x > 0$.
* Negativa  definidad: Para todo $x \in \mathbb{C}^n$, $x^T A x < 0$.
* no negativa definidad: Para todo $x \in \mathbb{C}^n$, $x^T A x  \ge 0$.

Esas definciones son equvalentes (tarea).

Teorema (tarea). Si $A$ es positiva definida, $A^{-1}$ es positiva definida.

Teorema Estrella: SVD: Singular Value Decomposition (Descomposicion en valores singulares).

Sea $A \in \mathbb{C}^{m \times n}$. Existe una matriz ortgonal $u \in \mathbb{C}^{m \times m}$, una matriz ortogonal $V \in \mathbb{C}^{n \times n}$ y una matriz real, diagonal $\Sigma \in \mathbb{R}^{m \times n}$ tales que

$$ A = U \Sigma V^* $$



Se usa mucho en ML para reduccion de dimensionalidad (PCA).

Prueba (Carnelius Lanczos). Asuma $A \in \mathbb{C}^{m \times n}$
y construimos una matriz auxiliar:


$$S = \begin{pmatrix} 0 \quad  |  \quad  A \\
------\\
A^*  \quad | \quad 0  \quad  \end{pmatrix}  $$

La matriz $S= \in \mathbb{C}^{(m+n) \times (m+n)}$ es autoadjunta. O sea que
los autovectores de $S$ son ortogonales y los autovalores son reales.


$$ S w_i = \lambda_i w_i \quad \quad (3) $$
Pero $w_i$ lo podemos partir como sigue

$$ \begin{pmatrix}  u_i \\ v_i \end{pmatrix} $$, $u_i \in \mathbb{C}^m$, $v_i \in \mathbb{C}^n$. La ecuacion (3) resulta

\begin{eqnarray}
A^* u_i &=& \lambda_i v_i  \quad (6)  \\
A v_i  &=& \lambda_i u_i   \quad (7)
\end{eqnarray}
Multiplicamos la primera ecuacion por $A$ y la segunda por $A^*$

\begin{eqnarray}
A A^* u_i &=& A \lambda_i v_i = \lambda_i \lambda_i u_i = \lambda_i^2 u_i \\
A^* A v_i &=& A^* (\lambda_i u_i) = \lambda_i A^* u_i = \lambda^2 v_i
\end{eqnarray}

No todos los autovlares son positivos. Sea $r$ el indice del ultimo que no es 0. $\lambda_1, \lambda_2, \cdots, \lambda_r, 0, 0 , 0 $. 

Construyamos la matrices $U_r$, y $V_r$ de los autvectores de ($A A^*$ y de $A^* A$ respectivamente, esas matrices tiene como columnas estos autvectores. 
Llamos $U_0$, $V_0$ las colas de matrices asosciadas con $\lambda_i=0$. 

Segun esta construccion: de (6, 2) 

\begin{eqnarray}
A^* U_r &=& V_r \Lambda_r  \quad , \quad A^* U_0 = 0 \\
A V_r &=& U_r \Lambda_r  \quad , \quad A V_0 = 0.
\end{eqnarray}

Construimos la matriz






In [2]:
import numpy as np

A=np.array( [[1,3,], [-2,4]])

dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [5]:
np.linalg.eig(A)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[0.77459667+0.j , 0.77459667-0.j ],
        [0.38729833+0.5j, 0.38729833-0.5j]]))

In [6]:
np.linalg.svd(A)

(array([[ 0.52573111,  0.85065081],
        [ 0.85065081, -0.52573111]]),
 array([5.11667274, 1.95439508]),
 array([[-0.22975292,  0.97324899],
        [ 0.97324899,  0.22975292]]))